// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package feedbackdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFeedbackIntake = `-- name: InsertFeedbackIntake :one
INSERT INTO wheretolive.feedback_intake (id,category_key,place_id,title,message,created_at,updated_at)
SELECT $1,c.key,$3,$4,$5,$6,$6 FROM wheretolive.feedback_categories c WHERE c.key=$2 AND c.active
RETURNING id, category_key, place_id, title, message, status, outcome, version, created_at, updated_at
`

type InsertFeedbackIntakeParams struct {
	ID        string      `json:"id"`
	Key       string      `json:"key"`
	PlaceID   pgtype.UUID `json:"place_id"`
	Title     string      `json:"title"`
	Message   string      `json:"message"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) InsertFeedbackIntake(ctx context.Context, arg InsertFeedbackIntakeParams) (WheretoliveFeedbackIntake, error) {
	row := q.db.QueryRow(ctx, insertFeedbackIntake,
		arg.ID,
		arg.Key,
		arg.PlaceID,
		arg.Title,
		arg.Message,
		arg.CreatedAt,
	)
	var i WheretoliveFeedbackIntake
	err := row.Scan(
		&i.ID,
		&i.CategoryKey,
		&i.PlaceID,
		&i.Title,
		&i.Message,
		&i.Status,
		&i.Outcome,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedbackCategories = `-- name: ListFeedbackCategories :many
SELECT key, label, active, position FROM wheretolive.feedback_categories WHERE active ORDER BY position,key
`

func (q *Queries) ListFeedbackCategories(ctx context.Context) ([]WheretoliveFeedbackCategory, error) {
	rows, err := q.db.Query(ctx, listFeedbackCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WheretoliveFeedbackCategory
	for rows.Next() {
		var i WheretoliveFeedbackCategory
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.Active,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackIntake = `-- name: ListFeedbackIntake :many
SELECT id, category_key, place_id, title, message, status, outcome, version, created_at, updated_at FROM wheretolive.feedback_intake
WHERE ($1::text = '' OR status = $1)
 AND ($2::text = '' OR category_key = $2)
ORDER BY created_at DESC,id DESC LIMIT $4 OFFSET $3
`

type ListFeedbackIntakeParams struct {
	Status      string `json:"status"`
	CategoryKey string `json:"category_key"`
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
}

func (q *Queries) ListFeedbackIntake(ctx context.Context, arg ListFeedbackIntakeParams) ([]WheretoliveFeedbackIntake, error) {
	rows, err := q.db.Query(ctx, listFeedbackIntake,
		arg.Status,
		arg.CategoryKey,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WheretoliveFeedbackIntake
	for rows.Next() {
		var i WheretoliveFeedbackIntake
		if err := rows.Scan(
			&i.ID,
			&i.CategoryKey,
			&i.PlaceID,
			&i.Title,
			&i.Message,
			&i.Status,
			&i.Outcome,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFeedbackIntake = `-- name: LockFeedbackIntake :one
SELECT id, category_key, place_id, title, message, status, outcome, version, created_at, updated_at FROM wheretolive.feedback_intake WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockFeedbackIntake(ctx context.Context, id string) (WheretoliveFeedbackIntake, error) {
	row := q.db.QueryRow(ctx, lockFeedbackIntake, id)
	var i WheretoliveFeedbackIntake
	err := row.Scan(
		&i.ID,
		&i.CategoryKey,
		&i.PlaceID,
		&i.Title,
		&i.Message,
		&i.Status,
		&i.Outcome,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reviewFeedbackIntake = `-- name: ReviewFeedbackIntake :one
UPDATE wheretolive.feedback_intake SET status=$2,outcome=$3,updated_at=$4,version=version+1
WHERE id=$1 AND version=$5 RETURNING id, category_key, place_id, title, message, status, outcome, version, created_at, updated_at
`

type ReviewFeedbackIntakeParams struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	Outcome   pgtype.Text `json:"outcome"`
	UpdatedAt time.Time   `json:"updated_at"`
	Version   int64       `json:"version"`
}

func (q *Queries) ReviewFeedbackIntake(ctx context.Context, arg ReviewFeedbackIntakeParams) (WheretoliveFeedbackIntake, error) {
	row := q.db.QueryRow(ctx, reviewFeedbackIntake,
		arg.ID,
		arg.Status,
		arg.Outcome,
		arg.UpdatedAt,
		arg.Version,
	)
	var i WheretoliveFeedbackIntake
	err := row.Scan(
		&i.ID,
		&i.CategoryKey,
		&i.PlaceID,
		&i.Title,
		&i.Message,
		&i.Status,
		&i.Outcome,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
