// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package auditdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPlatformAuditEvent = `-- name: InsertPlatformAuditEvent :exec
INSERT INTO wheretolive.audit_events
    (id, actor_type, actor_id, tenant_id, action, resource, resource_id, reason, result, correlation_id, occurred_at, before_state, after_state)
VALUES ($1, 'platform_administrator', $2, NULL, $3, $4, $5, $6, 'succeeded', $7, $8, $9, $10)
`

type InsertPlatformAuditEventParams struct {
	ID            string    `json:"id"`
	ActorID       string    `json:"actor_id"`
	Action        string    `json:"action"`
	Resource      string    `json:"resource"`
	ResourceID    string    `json:"resource_id"`
	Reason        string    `json:"reason"`
	CorrelationID string    `json:"correlation_id"`
	OccurredAt    time.Time `json:"occurred_at"`
	BeforeState   []byte    `json:"before_state"`
	AfterState    []byte    `json:"after_state"`
}

func (q *Queries) InsertPlatformAuditEvent(ctx context.Context, arg InsertPlatformAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertPlatformAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Reason,
		arg.CorrelationID,
		arg.OccurredAt,
		arg.BeforeState,
		arg.AfterState,
	)
	return err
}

const insertTenantAuditEvent = `-- name: InsertTenantAuditEvent :exec
INSERT INTO wheretolive.audit_events
    (id, actor_type, actor_id, tenant_id, action, resource, resource_id, reason, result, correlation_id, occurred_at, before_state, after_state)
VALUES ($1, 'tenant_user', $2, $3, $4, $5, $6, $7, 'succeeded', $8, $9, $10, $11)
`

type InsertTenantAuditEventParams struct {
	ID            string      `json:"id"`
	ActorID       string      `json:"actor_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Action        string      `json:"action"`
	Resource      string      `json:"resource"`
	ResourceID    string      `json:"resource_id"`
	Reason        string      `json:"reason"`
	CorrelationID string      `json:"correlation_id"`
	OccurredAt    time.Time   `json:"occurred_at"`
	BeforeState   []byte      `json:"before_state"`
	AfterState    []byte      `json:"after_state"`
}

func (q *Queries) InsertTenantAuditEvent(ctx context.Context, arg InsertTenantAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertTenantAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.TenantID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Reason,
		arg.CorrelationID,
		arg.OccurredAt,
		arg.BeforeState,
		arg.AfterState,
	)
	return err
}

const insertTenantScopedPlatformAuditEvent = `-- name: InsertTenantScopedPlatformAuditEvent :exec
INSERT INTO wheretolive.audit_events
    (id, actor_type, actor_id, tenant_id, action, resource, resource_id, reason, result, correlation_id, occurred_at, before_state, after_state)
VALUES ($1, 'platform_administrator', $2, $3, $4, $5, $6, $7, 'succeeded', $8, $9, $10, $11)
`

type InsertTenantScopedPlatformAuditEventParams struct {
	ID            string      `json:"id"`
	ActorID       string      `json:"actor_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Action        string      `json:"action"`
	Resource      string      `json:"resource"`
	ResourceID    string      `json:"resource_id"`
	Reason        string      `json:"reason"`
	CorrelationID string      `json:"correlation_id"`
	OccurredAt    time.Time   `json:"occurred_at"`
	BeforeState   []byte      `json:"before_state"`
	AfterState    []byte      `json:"after_state"`
}

func (q *Queries) InsertTenantScopedPlatformAuditEvent(ctx context.Context, arg InsertTenantScopedPlatformAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertTenantScopedPlatformAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.TenantID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Reason,
		arg.CorrelationID,
		arg.OccurredAt,
		arg.BeforeState,
		arg.AfterState,
	)
	return err
}
