// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package placesdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ModuraAuditEvent struct {
	ID            string      `json:"id"`
	ActorType     string      `json:"actor_type"`
	ActorID       string      `json:"actor_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Action        string      `json:"action"`
	Resource      string      `json:"resource"`
	ResourceID    string      `json:"resource_id"`
	Reason        string      `json:"reason"`
	Result        string      `json:"result"`
	CorrelationID string      `json:"correlation_id"`
	OccurredAt    time.Time   `json:"occurred_at"`
	BeforeState   []byte      `json:"before_state"`
	AfterState    []byte      `json:"after_state"`
}

type ModuraAuthLoginGuard struct {
	TenantSlug      string             `json:"tenant_slug"`
	NormalizedLogin string             `json:"normalized_login"`
	FailureCount    int32              `json:"failure_count"`
	WindowStartedAt time.Time          `json:"window_started_at"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type ModuraAuthOneTimeToken struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	UserID               string             `json:"user_id"`
	Purpose              string             `json:"purpose"`
	TokenHash            []byte             `json:"token_hash"`
	CreatedAt            time.Time          `json:"created_at"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	BoundEmail           pgtype.Text        `json:"bound_email"`
	BoundSecurityVersion pgtype.Int8        `json:"bound_security_version"`
}

type ModuraAuthRefreshTokenUse struct {
	TokenHash  []byte    `json:"token_hash"`
	SessionID  string    `json:"session_id"`
	FamilyID   string    `json:"family_id"`
	ConsumedAt time.Time `json:"consumed_at"`
}

type ModuraAuthSecurityEvent struct {
	ID            string      `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	UserID        pgtype.UUID `json:"user_id"`
	EventType     string      `json:"event_type"`
	CorrelationID string      `json:"correlation_id"`
	OccurredAt    time.Time   `json:"occurred_at"`
}

type ModuraAuthSession struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	UserID           string             `json:"user_id"`
	FamilyID         string             `json:"family_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	SecurityVersion  int64              `json:"security_version"`
	CreatedAt        time.Time          `json:"created_at"`
	LastUsedAt       time.Time          `json:"last_used_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
}

type ModuraCommunityIdentity struct {
	Singleton bool      `json:"singleton"`
	TenantID  string    `json:"tenant_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ModuraConfigurationDefinition struct {
	ID                string    `json:"id"`
	Key               string    `json:"key"`
	Name              string    `json:"name"`
	ValueType         string    `json:"value_type"`
	TenantOverridable bool      `json:"tenant_overridable"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ModuraDepartment struct {
	ID             string      `json:"id"`
	TenantID       string      `json:"tenant_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Name           string      `json:"name"`
	NormalizedName string      `json:"normalized_name"`
	SortOrder      int32       `json:"sort_order"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type ModuraGlobalConfigurationValue struct {
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ModuraGlobalDictionaryItem struct {
	ID               string    `json:"id"`
	DictionaryTypeID string    `json:"dictionary_type_id"`
	Code             string    `json:"code"`
	Label            string    `json:"label"`
	SortOrder        int32     `json:"sort_order"`
	Enabled          bool      `json:"enabled"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type ModuraGlobalDictionaryType struct {
	ID        string    `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ModuraIdentityMailQueue struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	UserID           string             `json:"user_id"`
	TokenID          string             `json:"token_id"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	CreatedAt        time.Time          `json:"created_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	AvailableAt      time.Time          `json:"available_at"`
	LeaseUntil       pgtype.Timestamptz `json:"lease_until"`
	Attempts         int32              `json:"attempts"`
}

type ModuraPlace struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Type           string             `json:"type"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	CountryCode    string             `json:"country_code"`
	Timezone       pgtype.Text        `json:"timezone"`
	Latitude       pgtype.Float8      `json:"latitude"`
	Longitude      pgtype.Float8      `json:"longitude"`
	Currency       pgtype.Text        `json:"currency"`
	Languages      []string           `json:"languages"`
	CoverageLevel  int16              `json:"coverage_level"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Version        int64              `json:"version"`
}

type ModuraPlaceAlias struct {
	PlaceID        string `json:"place_id"`
	Locale         string `json:"locale"`
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
	Preferred      bool   `json:"preferred"`
}

type ModuraPlatformAdministrator struct {
	ID                 string    `json:"id"`
	Username           string    `json:"username"`
	NormalizedUsername string    `json:"normalized_username"`
	PasswordHash       string    `json:"password_hash"`
	Status             string    `json:"status"`
	SecurityVersion    int64     `json:"security_version"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type ModuraPlatformAuthSession struct {
	ID               string             `json:"id"`
	AdministratorID  string             `json:"administrator_id"`
	FamilyID         string             `json:"family_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	SecurityVersion  int64              `json:"security_version"`
	CreatedAt        time.Time          `json:"created_at"`
	LastUsedAt       time.Time          `json:"last_used_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
}

type ModuraPlatformRefreshTokenUse struct {
	TokenHash  []byte    `json:"token_hash"`
	SessionID  string    `json:"session_id"`
	FamilyID   string    `json:"family_id"`
	ConsumedAt time.Time `json:"consumed_at"`
}

type ModuraPosition struct {
	ID             string    `json:"id"`
	TenantID       string    `json:"tenant_id"`
	Name           string    `json:"name"`
	NormalizedName string    `json:"normalized_name"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ModuraPublicIdentityEvent struct {
	ID            string      `json:"id"`
	TenantID      string      `json:"tenant_id"`
	UserID        pgtype.UUID `json:"user_id"`
	ActorKind     string      `json:"actor_kind"`
	Resource      string      `json:"resource"`
	ResourceID    string      `json:"resource_id"`
	Reason        string      `json:"reason"`
	Action        string      `json:"action"`
	Result        string      `json:"result"`
	CorrelationID string      `json:"correlation_id"`
	OccurredAt    time.Time   `json:"occurred_at"`
}

type ModuraPublicIdentityLimit struct {
	TenantID        string    `json:"tenant_id"`
	KeyHash         []byte    `json:"key_hash"`
	WindowStartedAt time.Time `json:"window_started_at"`
	Attempts        int32     `json:"attempts"`
}

type ModuraPublicPlace struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Type           string             `json:"type"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	CountryCode    string             `json:"country_code"`
	Timezone       pgtype.Text        `json:"timezone"`
	Latitude       pgtype.Float8      `json:"latitude"`
	Longitude      pgtype.Float8      `json:"longitude"`
	Currency       pgtype.Text        `json:"currency"`
	Languages      []string           `json:"languages"`
	CoverageLevel  int16              `json:"coverage_level"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type ModuraRole struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Reserved  bool      `json:"reserved"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Version   int64     `json:"version"`
}

type ModuraRolePolicy struct {
	TenantID  string    `json:"tenant_id"`
	RoleID    string    `json:"role_id"`
	Resource  string    `json:"resource"`
	Action    string    `json:"action"`
	DataScope string    `json:"data_scope"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ModuraRolePolicyDepartment struct {
	TenantID     string `json:"tenant_id"`
	RoleID       string `json:"role_id"`
	Resource     string `json:"resource"`
	Action       string `json:"action"`
	DepartmentID string `json:"department_id"`
}

type ModuraTenant struct {
	ID          string    `json:"id"`
	Slug        string    `json:"slug"`
	DisplayName string    `json:"display_name"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ModuraTenantConfigurationValue struct {
	TenantID  string    `json:"tenant_id"`
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ModuraTenantDictionaryItem struct {
	ID               string    `json:"id"`
	TenantID         string    `json:"tenant_id"`
	DictionaryTypeID string    `json:"dictionary_type_id"`
	Code             string    `json:"code"`
	Label            string    `json:"label"`
	SortOrder        int32     `json:"sort_order"`
	Enabled          bool      `json:"enabled"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type ModuraTenantDictionaryType struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ModuraTenantProvisioningRequest struct {
	IdempotencyKey string    `json:"idempotency_key"`
	RequestDigest  []byte    `json:"request_digest"`
	TenantID       string    `json:"tenant_id"`
	CreatedAt      time.Time `json:"created_at"`
	CompletedAt    time.Time `json:"completed_at"`
}

type ModuraUser struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Username           string             `json:"username"`
	NormalizedUsername string             `json:"normalized_username"`
	Email              pgtype.Text        `json:"email"`
	NormalizedEmail    pgtype.Text        `json:"normalized_email"`
	EmailVerifiedAt    pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	Status             string             `json:"status"`
	SecurityVersion    int64              `json:"security_version"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	Consumer           bool               `json:"consumer"`
}

type ModuraUserOrganization struct {
	TenantID            string      `json:"tenant_id"`
	UserID              string      `json:"user_id"`
	PrimaryDepartmentID string      `json:"primary_department_id"`
	PositionID          pgtype.UUID `json:"position_id"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

type ModuraUserRole struct {
	TenantID  string    `json:"tenant_id"`
	UserID    string    `json:"user_id"`
	RoleID    string    `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ModuraUserRoleVersion struct {
	TenantID  string    `json:"tenant_id"`
	UserID    string    `json:"user_id"`
	Version   int64     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}
