// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package placesdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPlaceAliases = `-- name: ClearPlaceAliases :exec
DELETE FROM wheretolive.place_aliases WHERE place_id=$1
`

func (q *Queries) ClearPlaceAliases(ctx context.Context, placeID string) error {
	_, err := q.db.Exec(ctx, clearPlaceAliases, placeID)
	return err
}

const getManagedPlace = `-- name: GetManagedPlace :one
SELECT id, slug, name, normalized_name, type, parent_id, country_code, timezone, latitude, longitude, currency, languages, coverage_level, published_at, created_at, updated_at, version FROM wheretolive.places WHERE id = $1
`

func (q *Queries) GetManagedPlace(ctx context.Context, id string) (WheretolivePlace, error) {
	row := q.db.QueryRow(ctx, getManagedPlace, id)
	var i WheretolivePlace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.ParentID,
		&i.CountryCode,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.Currency,
		&i.Languages,
		&i.CoverageLevel,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPublicPlace = `-- name: GetPublicPlace :one
SELECT p.id, p.slug, p.name, p.normalized_name, p.type, p.parent_id, p.country_code, p.timezone, p.latitude, p.longitude, p.currency, p.languages, p.coverage_level, p.published_at, p.created_at, p.updated_at, coalesce(a.name, p.name)::text AS display_name
FROM wheretolive.public_places p
LEFT JOIN wheretolive.place_aliases a ON a.place_id = p.id AND a.locale = $1 AND a.preferred
WHERE p.slug = $2
`

type GetPublicPlaceParams struct {
	Locale string `json:"locale"`
	Slug   string `json:"slug"`
}

type GetPublicPlaceRow struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Type           string             `json:"type"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	CountryCode    string             `json:"country_code"`
	Timezone       pgtype.Text        `json:"timezone"`
	Latitude       pgtype.Float8      `json:"latitude"`
	Longitude      pgtype.Float8      `json:"longitude"`
	Currency       pgtype.Text        `json:"currency"`
	Languages      []string           `json:"languages"`
	CoverageLevel  int16              `json:"coverage_level"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DisplayName    string             `json:"display_name"`
}

func (q *Queries) GetPublicPlace(ctx context.Context, arg GetPublicPlaceParams) (GetPublicPlaceRow, error) {
	row := q.db.QueryRow(ctx, getPublicPlace, arg.Locale, arg.Slug)
	var i GetPublicPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.ParentID,
		&i.CountryCode,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.Currency,
		&i.Languages,
		&i.CoverageLevel,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const hasUnpublishedAncestor = `-- name: HasUnpublishedAncestor :one
WITH RECURSIVE ancestors AS (
  SELECT root.parent_id FROM wheretolive.places root WHERE root.id=$2
  UNION ALL
  SELECT p.parent_id FROM wheretolive.places p JOIN ancestors a ON p.id=a.parent_id
)
SELECT EXISTS (SELECT 1 FROM ancestors a JOIN wheretolive.places p ON p.id=a.parent_id WHERE p.published_at IS NULL OR p.published_at > $1::timestamptz)
`

type HasUnpublishedAncestorParams struct {
	Now     time.Time `json:"now"`
	PlaceID string    `json:"place_id"`
}

func (q *Queries) HasUnpublishedAncestor(ctx context.Context, arg HasUnpublishedAncestorParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnpublishedAncestor, arg.Now, arg.PlaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertManagedPlace = `-- name: InsertManagedPlace :one
INSERT INTO wheretolive.places (id,slug,name,normalized_name,type,parent_id,country_code,timezone,latitude,longitude,currency,languages,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13) RETURNING id, slug, name, normalized_name, type, parent_id, country_code, timezone, latitude, longitude, currency, languages, coverage_level, published_at, created_at, updated_at, version
`

type InsertManagedPlaceParams struct {
	ID             string        `json:"id"`
	Slug           string        `json:"slug"`
	Name           string        `json:"name"`
	NormalizedName string        `json:"normalized_name"`
	Type           string        `json:"type"`
	ParentID       pgtype.UUID   `json:"parent_id"`
	CountryCode    string        `json:"country_code"`
	Timezone       pgtype.Text   `json:"timezone"`
	Latitude       pgtype.Float8 `json:"latitude"`
	Longitude      pgtype.Float8 `json:"longitude"`
	Currency       pgtype.Text   `json:"currency"`
	Languages      []string      `json:"languages"`
	CreatedAt      time.Time     `json:"created_at"`
}

func (q *Queries) InsertManagedPlace(ctx context.Context, arg InsertManagedPlaceParams) (WheretolivePlace, error) {
	row := q.db.QueryRow(ctx, insertManagedPlace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.NormalizedName,
		arg.Type,
		arg.ParentID,
		arg.CountryCode,
		arg.Timezone,
		arg.Latitude,
		arg.Longitude,
		arg.Currency,
		arg.Languages,
		arg.CreatedAt,
	)
	var i WheretolivePlace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.ParentID,
		&i.CountryCode,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.Currency,
		&i.Languages,
		&i.CoverageLevel,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertPlaceAlias = `-- name: InsertPlaceAlias :exec
INSERT INTO wheretolive.place_aliases (place_id,locale,name,normalized_name,preferred) VALUES ($1,$2,$3,$4,$5)
`

type InsertPlaceAliasParams struct {
	PlaceID        string `json:"place_id"`
	Locale         string `json:"locale"`
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
	Preferred      bool   `json:"preferred"`
}

func (q *Queries) InsertPlaceAlias(ctx context.Context, arg InsertPlaceAliasParams) error {
	_, err := q.db.Exec(ctx, insertPlaceAlias,
		arg.PlaceID,
		arg.Locale,
		arg.Name,
		arg.NormalizedName,
		arg.Preferred,
	)
	return err
}

const listManagedPlaces = `-- name: ListManagedPlaces :many
SELECT p.id, p.slug, p.name, p.normalized_name, p.type, p.parent_id, p.country_code, p.timezone, p.latitude, p.longitude, p.currency, p.languages, p.coverage_level, p.published_at, p.created_at, p.updated_at, p.version FROM wheretolive.places p
WHERE ($1::text = '' OR p.normalized_name LIKE $2::text ESCAPE '\'
   OR p.slug LIKE $2::text ESCAPE '\'
   OR EXISTS (SELECT 1 FROM wheretolive.place_aliases a WHERE a.place_id=p.id
       AND a.normalized_name LIKE $2::text ESCAPE '\'))
 AND ($3::text = '' OR p.country_code = $3)
 AND ($4::smallint IS NULL OR p.coverage_level = $4)
 AND ($5::text = ''
      OR ($5 = 'draft' AND p.published_at IS NULL)
      OR ($5 = 'published' AND p.published_at IS NOT NULL))
ORDER BY p.slug LIMIT $7 OFFSET $6
`

type ListManagedPlacesParams struct {
	Search        string      `json:"search"`
	Prefix        string      `json:"prefix"`
	CountryCode   string      `json:"country_code"`
	CoverageLevel pgtype.Int2 `json:"coverage_level"`
	Publication   string      `json:"publication"`
	PageOffset    int32       `json:"page_offset"`
	PageLimit     int32       `json:"page_limit"`
}

func (q *Queries) ListManagedPlaces(ctx context.Context, arg ListManagedPlacesParams) ([]WheretolivePlace, error) {
	rows, err := q.db.Query(ctx, listManagedPlaces,
		arg.Search,
		arg.Prefix,
		arg.CountryCode,
		arg.CoverageLevel,
		arg.Publication,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WheretolivePlace
	for rows.Next() {
		var i WheretolivePlace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.NormalizedName,
			&i.Type,
			&i.ParentID,
			&i.CountryCode,
			&i.Timezone,
			&i.Latitude,
			&i.Longitude,
			&i.Currency,
			&i.Languages,
			&i.CoverageLevel,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceAliases = `-- name: ListPlaceAliases :many
SELECT locale, name, preferred FROM wheretolive.place_aliases WHERE place_id=$1 ORDER BY locale, normalized_name
`

type ListPlaceAliasesRow struct {
	Locale    string `json:"locale"`
	Name      string `json:"name"`
	Preferred bool   `json:"preferred"`
}

func (q *Queries) ListPlaceAliases(ctx context.Context, placeID string) ([]ListPlaceAliasesRow, error) {
	rows, err := q.db.Query(ctx, listPlaceAliases, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaceAliasesRow
	for rows.Next() {
		var i ListPlaceAliasesRow
		if err := rows.Scan(&i.Locale, &i.Name, &i.Preferred); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockManagedPlace = `-- name: LockManagedPlace :one
SELECT id, slug, name, normalized_name, type, parent_id, country_code, timezone, latitude, longitude, currency, languages, coverage_level, published_at, created_at, updated_at, version FROM wheretolive.places WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockManagedPlace(ctx context.Context, id string) (WheretolivePlace, error) {
	row := q.db.QueryRow(ctx, lockManagedPlace, id)
	var i WheretolivePlace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.ParentID,
		&i.CountryCode,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.Currency,
		&i.Languages,
		&i.CoverageLevel,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const lockPlacePublicationTree = `-- name: LockPlacePublicationTree :exec
SELECT pg_advisory_xact_lock(1297040470)
`

func (q *Queries) LockPlacePublicationTree(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPlacePublicationTree)
	return err
}

const searchPublicPlaces = `-- name: SearchPublicPlaces :many
SELECT p.id, p.slug, p.name, p.normalized_name, p.type, p.parent_id, p.country_code, p.timezone, p.latitude, p.longitude, p.currency, p.languages, p.coverage_level, p.published_at, p.created_at, p.updated_at, coalesce(a.name, p.name)::text AS display_name
FROM wheretolive.public_places p
LEFT JOIN wheretolive.place_aliases a ON a.place_id = p.id AND a.locale = $1 AND a.preferred
WHERE $2::text = ''
   OR p.normalized_name LIKE $3::text ESCAPE '\'
   OR p.slug LIKE $3::text ESCAPE '\'
   OR p.normalized_name % $2::text
   OR EXISTS (
       SELECT 1 FROM wheretolive.place_aliases alias WHERE alias.place_id = p.id
       AND (alias.normalized_name LIKE $3::text ESCAPE '\' OR alias.normalized_name % $2::text)
   )
ORDER BY CASE WHEN p.slug = $2 OR p.normalized_name = $2
    OR EXISTS (SELECT 1 FROM wheretolive.place_aliases exact WHERE exact.place_id = p.id AND exact.normalized_name = $2)
    THEN 0 ELSE 1 END, p.slug
LIMIT $5 OFFSET $4
`

type SearchPublicPlacesParams struct {
	Locale     string `json:"locale"`
	Search     string `json:"search"`
	Prefix     string `json:"prefix"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type SearchPublicPlacesRow struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Type           string             `json:"type"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	CountryCode    string             `json:"country_code"`
	Timezone       pgtype.Text        `json:"timezone"`
	Latitude       pgtype.Float8      `json:"latitude"`
	Longitude      pgtype.Float8      `json:"longitude"`
	Currency       pgtype.Text        `json:"currency"`
	Languages      []string           `json:"languages"`
	CoverageLevel  int16              `json:"coverage_level"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DisplayName    string             `json:"display_name"`
}

func (q *Queries) SearchPublicPlaces(ctx context.Context, arg SearchPublicPlacesParams) ([]SearchPublicPlacesRow, error) {
	rows, err := q.db.Query(ctx, searchPublicPlaces,
		arg.Locale,
		arg.Search,
		arg.Prefix,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPublicPlacesRow
	for rows.Next() {
		var i SearchPublicPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.NormalizedName,
			&i.Type,
			&i.ParentID,
			&i.CountryCode,
			&i.Timezone,
			&i.Latitude,
			&i.Longitude,
			&i.Currency,
			&i.Languages,
			&i.CoverageLevel,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlacePublication = `-- name: SetPlacePublication :one
UPDATE wheretolive.places SET published_at=$2,coverage_level=CASE WHEN $2::timestamptz IS NOT NULL THEN greatest(coverage_level,1) ELSE coverage_level END,updated_at=$3,version=version+1
WHERE id=$1 AND version=$4 RETURNING id, slug, name, normalized_name, type, parent_id, country_code, timezone, latitude, longitude, currency, languages, coverage_level, published_at, created_at, updated_at, version
`

type SetPlacePublicationParams struct {
	ID          string             `json:"id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	Version     int64              `json:"version"`
}

func (q *Queries) SetPlacePublication(ctx context.Context, arg SetPlacePublicationParams) (WheretolivePlace, error) {
	row := q.db.QueryRow(ctx, setPlacePublication,
		arg.ID,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i WheretolivePlace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.ParentID,
		&i.CountryCode,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.Currency,
		&i.Languages,
		&i.CoverageLevel,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateManagedPlace = `-- name: UpdateManagedPlace :one
UPDATE wheretolive.places SET name=$2,normalized_name=$3,timezone=$4,latitude=$5,longitude=$6,currency=$7,languages=$8,updated_at=$9,version=version+1
WHERE id=$1 AND version=$10 RETURNING id, slug, name, normalized_name, type, parent_id, country_code, timezone, latitude, longitude, currency, languages, coverage_level, published_at, created_at, updated_at, version
`

type UpdateManagedPlaceParams struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	NormalizedName string        `json:"normalized_name"`
	Timezone       pgtype.Text   `json:"timezone"`
	Latitude       pgtype.Float8 `json:"latitude"`
	Longitude      pgtype.Float8 `json:"longitude"`
	Currency       pgtype.Text   `json:"currency"`
	Languages      []string      `json:"languages"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Version        int64         `json:"version"`
}

func (q *Queries) UpdateManagedPlace(ctx context.Context, arg UpdateManagedPlaceParams) (WheretolivePlace, error) {
	row := q.db.QueryRow(ctx, updateManagedPlace,
		arg.ID,
		arg.Name,
		arg.NormalizedName,
		arg.Timezone,
		arg.Latitude,
		arg.Longitude,
		arg.Currency,
		arg.Languages,
		arg.UpdatedAt,
		arg.Version,
	)
	var i WheretolivePlace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.ParentID,
		&i.CountryCode,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.Currency,
		&i.Languages,
		&i.CoverageLevel,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
