// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package identitydb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProvisioningTenant = `-- name: ActivateProvisioningTenant :execrows
UPDATE modura.tenants
SET status = 'active', updated_at = $2
WHERE id = $1 AND status = 'provisioning'
`

type ActivateProvisioningTenantParams struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ActivateProvisioningTenant(ctx context.Context, arg ActivateProvisioningTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateProvisioningTenant, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyInvitationActivation = `-- name: ApplyInvitationActivation :exec
UPDATE modura.users
SET password_hash = $3, security_version = security_version + 1, status = 'active',
    email_verified_at = CASE WHEN email IS NULL THEN NULL ELSE COALESCE(email_verified_at, $4) END,
    updated_at = $4
WHERE tenant_id = $1 AND id = $2
`

type ApplyInvitationActivationParams struct {
	TenantID     string      `json:"tenant_id"`
	ID           string      `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) ApplyInvitationActivation(ctx context.Context, arg ApplyInvitationActivationParams) error {
	_, err := q.db.Exec(ctx, applyInvitationActivation,
		arg.TenantID,
		arg.ID,
		arg.PasswordHash,
		arg.UpdatedAt,
	)
	return err
}

const applyPasswordChange = `-- name: ApplyPasswordChange :execrows
UPDATE modura.users
SET password_hash = $3, security_version = $4, updated_at = $5
WHERE tenant_id = $1 AND id = $2
`

type ApplyPasswordChangeParams struct {
	TenantID        string      `json:"tenant_id"`
	ID              string      `json:"id"`
	PasswordHash    pgtype.Text `json:"password_hash"`
	SecurityVersion int64       `json:"security_version"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) ApplyPasswordChange(ctx context.Context, arg ApplyPasswordChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyPasswordChange,
		arg.TenantID,
		arg.ID,
		arg.PasswordHash,
		arg.SecurityVersion,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyPasswordReset = `-- name: ApplyPasswordReset :exec
UPDATE modura.users
SET password_hash = $3, security_version = security_version + 1, updated_at = $4
WHERE tenant_id = $1 AND id = $2
`

type ApplyPasswordResetParams struct {
	TenantID     string      `json:"tenant_id"`
	ID           string      `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) ApplyPasswordReset(ctx context.Context, arg ApplyPasswordResetParams) error {
	_, err := q.db.Exec(ctx, applyPasswordReset,
		arg.TenantID,
		arg.ID,
		arg.PasswordHash,
		arg.UpdatedAt,
	)
	return err
}

const clearLoginGuard = `-- name: ClearLoginGuard :execrows
DELETE FROM modura.auth_login_guard
WHERE tenant_slug = $1 AND normalized_login = $2
`

type ClearLoginGuardParams struct {
	TenantSlug      string `json:"tenant_slug"`
	NormalizedLogin string `json:"normalized_login"`
}

func (q *Queries) ClearLoginGuard(ctx context.Context, arg ClearLoginGuardParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearLoginGuard, arg.TenantSlug, arg.NormalizedLogin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOneTimeTokenRow = `-- name: ConsumeOneTimeTokenRow :execrows
UPDATE modura.auth_one_time_tokens
SET consumed_at = $2
WHERE token_hash = $1
`

type ConsumeOneTimeTokenRowParams struct {
	TokenHash  []byte             `json:"token_hash"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

func (q *Queries) ConsumeOneTimeTokenRow(ctx context.Context, arg ConsumeOneTimeTokenRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOneTimeTokenRow, arg.TokenHash, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeTenantUserOneTimeTokens = `-- name: ConsumeTenantUserOneTimeTokens :exec
UPDATE modura.auth_one_time_tokens
SET consumed_at = $3
WHERE tenant_id = $1 AND user_id = $2 AND consumed_at IS NULL
`

type ConsumeTenantUserOneTimeTokensParams struct {
	TenantID   string             `json:"tenant_id"`
	UserID     string             `json:"user_id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

func (q *Queries) ConsumeTenantUserOneTimeTokens(ctx context.Context, arg ConsumeTenantUserOneTimeTokensParams) error {
	_, err := q.db.Exec(ctx, consumeTenantUserOneTimeTokens, arg.TenantID, arg.UserID, arg.ConsumedAt)
	return err
}

const disableTenantUser = `-- name: DisableTenantUser :execrows
UPDATE modura.users
SET status = 'disabled', security_version = security_version + 1, updated_at = $3
WHERE tenant_id = $1 AND id = $2 AND status <> 'disabled'
`

type DisableTenantUserParams struct {
	TenantID  string    `json:"tenant_id"`
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) DisableTenantUser(ctx context.Context, arg DisableTenantUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableTenantUser, arg.TenantID, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAdministratorInvitation = `-- name: InsertAdministratorInvitation :exec
INSERT INTO modura.auth_one_time_tokens
    (id, tenant_id, user_id, purpose, token_hash, created_at, expires_at)
VALUES ($1, $2, $3, 'invitation', $4, $5, $6)
`

type InsertAdministratorInvitationParams struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	UserID    string    `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertAdministratorInvitation(ctx context.Context, arg InsertAdministratorInvitationParams) error {
	_, err := q.db.Exec(ctx, insertAdministratorInvitation,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertAuthSecurityEvent = `-- name: InsertAuthSecurityEvent :exec
INSERT INTO modura.auth_security_events (id, tenant_id, user_id, event_type, correlation_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuthSecurityEventParams struct {
	ID            string      `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	UserID        pgtype.UUID `json:"user_id"`
	EventType     string      `json:"event_type"`
	CorrelationID string      `json:"correlation_id"`
	OccurredAt    time.Time   `json:"occurred_at"`
}

func (q *Queries) InsertAuthSecurityEvent(ctx context.Context, arg InsertAuthSecurityEventParams) error {
	_, err := q.db.Exec(ctx, insertAuthSecurityEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.EventType,
		arg.CorrelationID,
		arg.OccurredAt,
	)
	return err
}

const insertAuthSession = `-- name: InsertAuthSession :exec
INSERT INTO modura.auth_sessions
    (id, tenant_id, user_id, family_id, refresh_token_hash, security_version, created_at, last_used_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7, $8)
`

type InsertAuthSessionParams struct {
	ID               string    `json:"id"`
	TenantID         string    `json:"tenant_id"`
	UserID           string    `json:"user_id"`
	FamilyID         string    `json:"family_id"`
	RefreshTokenHash []byte    `json:"refresh_token_hash"`
	SecurityVersion  int64     `json:"security_version"`
	CreatedAt        time.Time `json:"created_at"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) InsertAuthSession(ctx context.Context, arg InsertAuthSessionParams) error {
	_, err := q.db.Exec(ctx, insertAuthSession,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.FamilyID,
		arg.RefreshTokenHash,
		arg.SecurityVersion,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertInvitedAdministrator = `-- name: InsertInvitedAdministrator :exec
INSERT INTO modura.users
    (id, tenant_id, username, normalized_username, email, normalized_email, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'invited', $7, $7)
`

type InsertInvitedAdministratorParams struct {
	ID                 string      `json:"id"`
	TenantID           string      `json:"tenant_id"`
	Username           string      `json:"username"`
	NormalizedUsername string      `json:"normalized_username"`
	Email              pgtype.Text `json:"email"`
	NormalizedEmail    pgtype.Text `json:"normalized_email"`
	CreatedAt          time.Time   `json:"created_at"`
}

func (q *Queries) InsertInvitedAdministrator(ctx context.Context, arg InsertInvitedAdministratorParams) error {
	_, err := q.db.Exec(ctx, insertInvitedAdministrator,
		arg.ID,
		arg.TenantID,
		arg.Username,
		arg.NormalizedUsername,
		arg.Email,
		arg.NormalizedEmail,
		arg.CreatedAt,
	)
	return err
}

const insertOneTimeToken = `-- name: InsertOneTimeToken :execrows
INSERT INTO modura.auth_one_time_tokens
    (id, tenant_id, user_id, purpose, token_hash, created_at, expires_at)
SELECT $1, u.tenant_id, u.id, $4, $5, $6, $7
FROM modura.users u
JOIN modura.tenants t ON t.id = u.tenant_id
WHERE u.tenant_id = $2 AND u.id = $3 AND t.status = 'active'
  AND (($4 = 'invitation' AND u.status = 'invited') OR ($4 = 'password_reset' AND u.status = 'active'))
`

type InsertOneTimeTokenParams struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	ID_2      string    `json:"id_2"`
	Purpose   string    `json:"purpose"`
	TokenHash []byte    `json:"token_hash"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertOneTimeToken(ctx context.Context, arg InsertOneTimeTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOneTimeToken,
		arg.ID,
		arg.TenantID,
		arg.ID_2,
		arg.Purpose,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProvisioningTenant = `-- name: InsertProvisioningTenant :exec
INSERT INTO modura.tenants (id, slug, display_name, status, created_at, updated_at)
VALUES ($1, $2, $3, 'provisioning', $4, $4)
`

type InsertProvisioningTenantParams struct {
	ID          string    `json:"id"`
	Slug        string    `json:"slug"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertProvisioningTenant(ctx context.Context, arg InsertProvisioningTenantParams) error {
	_, err := q.db.Exec(ctx, insertProvisioningTenant,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const invalidateOneTimeTokens = `-- name: InvalidateOneTimeTokens :exec
UPDATE modura.auth_one_time_tokens
SET consumed_at = $4
WHERE tenant_id = $1 AND user_id = $2 AND purpose = $3 AND consumed_at IS NULL
`

type InvalidateOneTimeTokensParams struct {
	TenantID   string             `json:"tenant_id"`
	UserID     string             `json:"user_id"`
	Purpose    string             `json:"purpose"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

func (q *Queries) InvalidateOneTimeTokens(ctx context.Context, arg InvalidateOneTimeTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateOneTimeTokens,
		arg.TenantID,
		arg.UserID,
		arg.Purpose,
		arg.ConsumedAt,
	)
	return err
}

const listTenantSummaries = `-- name: ListTenantSummaries :many
SELECT id, slug, display_name, status, created_at, updated_at
FROM modura.tenants
ORDER BY created_at, id
`

func (q *Queries) ListTenantSummaries(ctx context.Context) ([]ModuraTenant, error) {
	rows, err := q.db.Query(ctx, listTenantSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModuraTenant
	for rows.Next() {
		var i ModuraTenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCurrentSession = `-- name: LockCurrentSession :one
SELECT s.id, s.tenant_id, s.user_id, s.security_version, s.family_id, s.expires_at
FROM modura.auth_sessions s
JOIN modura.users u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
JOIN modura.tenants t ON t.id = s.tenant_id
WHERE s.refresh_token_hash = $1 AND s.revoked_at IS NULL
  AND u.status = 'active' AND u.security_version = s.security_version AND t.status = 'active'
FOR UPDATE OF s
`

type LockCurrentSessionRow struct {
	ID              string    `json:"id"`
	TenantID        string    `json:"tenant_id"`
	UserID          string    `json:"user_id"`
	SecurityVersion int64     `json:"security_version"`
	FamilyID        string    `json:"family_id"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) LockCurrentSession(ctx context.Context, refreshTokenHash []byte) (LockCurrentSessionRow, error) {
	row := q.db.QueryRow(ctx, lockCurrentSession, refreshTokenHash)
	var i LockCurrentSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.SecurityVersion,
		&i.FamilyID,
		&i.ExpiresAt,
	)
	return i, err
}

const lockOneTimeToken = `-- name: LockOneTimeToken :one
SELECT tok.tenant_id, tok.user_id, tok.expires_at
FROM modura.auth_one_time_tokens tok
JOIN modura.users u ON u.tenant_id = tok.tenant_id AND u.id = tok.user_id
JOIN modura.tenants t ON t.id = tok.tenant_id
WHERE tok.token_hash = $1 AND tok.purpose = $2 AND tok.consumed_at IS NULL
  AND t.status = 'active'
  AND (($2 = 'invitation' AND u.status = 'invited') OR ($2 = 'password_reset' AND u.status = 'active'))
FOR UPDATE OF tok, u
`

type LockOneTimeTokenParams struct {
	TokenHash []byte `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

type LockOneTimeTokenRow struct {
	TenantID  string    `json:"tenant_id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) LockOneTimeToken(ctx context.Context, arg LockOneTimeTokenParams) (LockOneTimeTokenRow, error) {
	row := q.db.QueryRow(ctx, lockOneTimeToken, arg.TokenHash, arg.Purpose)
	var i LockOneTimeTokenRow
	err := row.Scan(&i.TenantID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const lockPasswordChange = `-- name: LockPasswordChange :one
SELECT s.family_id, u.security_version
FROM modura.auth_sessions s
JOIN modura.users u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
JOIN modura.tenants t ON t.id = s.tenant_id
WHERE s.id = $1 AND s.tenant_id = $2 AND s.user_id = $3
  AND s.refresh_token_hash = $4 AND s.revoked_at IS NULL AND s.expires_at > $5
  AND u.password_hash = $6 AND u.status = 'active' AND t.status = 'active'
FOR UPDATE OF s, u
`

type LockPasswordChangeParams struct {
	ID               string      `json:"id"`
	TenantID         string      `json:"tenant_id"`
	UserID           string      `json:"user_id"`
	RefreshTokenHash []byte      `json:"refresh_token_hash"`
	ExpiresAt        time.Time   `json:"expires_at"`
	PasswordHash     pgtype.Text `json:"password_hash"`
}

type LockPasswordChangeRow struct {
	FamilyID        string `json:"family_id"`
	SecurityVersion int64  `json:"security_version"`
}

func (q *Queries) LockPasswordChange(ctx context.Context, arg LockPasswordChangeParams) (LockPasswordChangeRow, error) {
	row := q.db.QueryRow(ctx, lockPasswordChange,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.PasswordHash,
	)
	var i LockPasswordChangeRow
	err := row.Scan(&i.FamilyID, &i.SecurityVersion)
	return i, err
}

const lockSelfProfile = `-- name: LockSelfProfile :one
SELECT u.id, u.username, u.email, u.status, u.updated_at
FROM modura.users u
JOIN modura.auth_sessions s ON s.tenant_id = u.tenant_id AND s.user_id = u.id
WHERE u.tenant_id = $1 AND u.id = $2 AND s.id = $3 AND u.status = 'active' AND s.revoked_at IS NULL
FOR UPDATE OF u
`

type LockSelfProfileParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
	ID_2     string `json:"id_2"`
}

type LockSelfProfileRow struct {
	ID        string      `json:"id"`
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	Status    string      `json:"status"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) LockSelfProfile(ctx context.Context, arg LockSelfProfileParams) (LockSelfProfileRow, error) {
	row := q.db.QueryRow(ctx, lockSelfProfile, arg.TenantID, arg.ID, arg.ID_2)
	var i LockSelfProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTenantProfile = `-- name: LockTenantProfile :one
SELECT slug, display_name, status, updated_at
FROM modura.tenants
WHERE id = $1
FOR UPDATE
`

type LockTenantProfileRow struct {
	Slug        string    `json:"slug"`
	DisplayName string    `json:"display_name"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) LockTenantProfile(ctx context.Context, id string) (LockTenantProfileRow, error) {
	row := q.db.QueryRow(ctx, lockTenantProfile, id)
	var i LockTenantProfileRow
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const loginGuardLockedUntil = `-- name: LoginGuardLockedUntil :one
SELECT locked_until
FROM modura.auth_login_guard
WHERE tenant_slug = $1 AND normalized_login = $2
`

type LoginGuardLockedUntilParams struct {
	TenantSlug      string `json:"tenant_slug"`
	NormalizedLogin string `json:"normalized_login"`
}

func (q *Queries) LoginGuardLockedUntil(ctx context.Context, arg LoginGuardLockedUntilParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, loginGuardLockedUntil, arg.TenantSlug, arg.NormalizedLogin)
	var locked_until pgtype.Timestamptz
	err := row.Scan(&locked_until)
	return locked_until, err
}

const passwordHashBySession = `-- name: PasswordHashBySession :one
SELECT u.password_hash
FROM modura.users u
JOIN modura.auth_sessions s ON s.tenant_id = u.tenant_id AND s.user_id = u.id
JOIN modura.tenants t ON t.id = u.tenant_id
WHERE u.tenant_id = $1 AND u.id = $2 AND s.id = $3
  AND u.status = 'active' AND t.status = 'active' AND s.revoked_at IS NULL
`

type PasswordHashBySessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
	ID_2     string `json:"id_2"`
}

func (q *Queries) PasswordHashBySession(ctx context.Context, arg PasswordHashBySessionParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, passwordHashBySession, arg.TenantID, arg.ID, arg.ID_2)
	var password_hash pgtype.Text
	err := row.Scan(&password_hash)
	return password_hash, err
}

const profileBySession = `-- name: ProfileBySession :one
SELECT u.id, u.username, u.email, u.status, u.updated_at
FROM modura.users u
JOIN modura.auth_sessions s ON s.tenant_id = u.tenant_id AND s.user_id = u.id
WHERE u.tenant_id = $1 AND u.id = $2 AND s.id = $3 AND u.status = 'active' AND s.revoked_at IS NULL
`

type ProfileBySessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
	ID_2     string `json:"id_2"`
}

type ProfileBySessionRow struct {
	ID        string      `json:"id"`
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	Status    string      `json:"status"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) ProfileBySession(ctx context.Context, arg ProfileBySessionParams) (ProfileBySessionRow, error) {
	row := q.db.QueryRow(ctx, profileBySession, arg.TenantID, arg.ID, arg.ID_2)
	var i ProfileBySessionRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
INSERT INTO modura.auth_login_guard
    (tenant_slug, normalized_login, failure_count, window_started_at, locked_until, updated_at)
VALUES ($1, $2, 1, $3::timestamptz, NULL, $3::timestamptz)
ON CONFLICT (tenant_slug, normalized_login) DO UPDATE
SET failure_count = CASE
        WHEN modura.auth_login_guard.window_started_at >= $4::timestamptz THEN modura.auth_login_guard.failure_count + 1
        ELSE 1 END,
    window_started_at = CASE
        WHEN modura.auth_login_guard.window_started_at >= $4::timestamptz THEN modura.auth_login_guard.window_started_at
        ELSE $3::timestamptz END,
    locked_until = CASE
        WHEN (
            CASE WHEN modura.auth_login_guard.window_started_at >= $4::timestamptz THEN modura.auth_login_guard.failure_count + 1
            ELSE 1 END
        ) >= $5::int THEN $6::timestamptz
        ELSE NULL END,
    updated_at = $3::timestamptz
RETURNING failure_count, locked_until
`

type RecordLoginFailureParams struct {
	TenantSlug      string    `json:"tenant_slug"`
	NormalizedLogin string    `json:"normalized_login"`
	Now             time.Time `json:"now"`
	Cutoff          time.Time `json:"cutoff"`
	Threshold       int32     `json:"threshold"`
	LockUntil       time.Time `json:"lock_until"`
}

type RecordLoginFailureRow struct {
	FailureCount int32              `json:"failure_count"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure,
		arg.TenantSlug,
		arg.NormalizedLogin,
		arg.Now,
		arg.Cutoff,
		arg.Threshold,
		arg.LockUntil,
	)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailureCount, &i.LockedUntil)
	return i, err
}

const recordRefreshTokenUse = `-- name: RecordRefreshTokenUse :exec
INSERT INTO modura.auth_refresh_token_uses (token_hash, session_id, family_id, consumed_at)
VALUES ($1, $2, $3, $4)
`

type RecordRefreshTokenUseParams struct {
	TokenHash  []byte    `json:"token_hash"`
	SessionID  string    `json:"session_id"`
	FamilyID   string    `json:"family_id"`
	ConsumedAt time.Time `json:"consumed_at"`
}

func (q *Queries) RecordRefreshTokenUse(ctx context.Context, arg RecordRefreshTokenUseParams) error {
	_, err := q.db.Exec(ctx, recordRefreshTokenUse,
		arg.TokenHash,
		arg.SessionID,
		arg.FamilyID,
		arg.ConsumedAt,
	)
	return err
}

const replayedTokenFamily = `-- name: ReplayedTokenFamily :one
SELECT family_id
FROM modura.auth_refresh_token_uses
WHERE token_hash = $1
`

func (q *Queries) ReplayedTokenFamily(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, replayedTokenFamily, tokenHash)
	var family_id string
	err := row.Scan(&family_id)
	return family_id, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE modura.auth_sessions
SET revoked_at = $3, revocation_reason = $4
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	TenantID         string             `json:"tenant_id"`
	UserID           string             `json:"user_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions,
		arg.TenantID,
		arg.UserID,
		arg.RevokedAt,
		arg.RevocationReason,
	)
	return err
}

const revokeFamilySessions = `-- name: RevokeFamilySessions :execrows
UPDATE modura.auth_sessions
SET revoked_at = $2, revocation_reason = 'refresh_reuse'
WHERE family_id = $1 AND revoked_at IS NULL
`

type RevokeFamilySessionsParams struct {
	FamilyID  string             `json:"family_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeFamilySessions(ctx context.Context, arg RevokeFamilySessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeFamilySessions, arg.FamilyID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsExcept = `-- name: RevokeSessionsExcept :exec
UPDATE modura.auth_sessions
SET revoked_at = $4, revocation_reason = $5
WHERE tenant_id = $1 AND user_id = $2 AND id <> $3 AND revoked_at IS NULL
`

type RevokeSessionsExceptParams struct {
	TenantID         string             `json:"tenant_id"`
	UserID           string             `json:"user_id"`
	ID               string             `json:"id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
}

func (q *Queries) RevokeSessionsExcept(ctx context.Context, arg RevokeSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsExcept,
		arg.TenantID,
		arg.UserID,
		arg.ID,
		arg.RevokedAt,
		arg.RevocationReason,
	)
	return err
}

const revokeTenantUserSessions = `-- name: RevokeTenantUserSessions :exec
UPDATE modura.auth_sessions
SET revoked_at = $3, revocation_reason = $4
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeTenantUserSessionsParams struct {
	TenantID         string             `json:"tenant_id"`
	UserID           string             `json:"user_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
}

func (q *Queries) RevokeTenantUserSessions(ctx context.Context, arg RevokeTenantUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeTenantUserSessions,
		arg.TenantID,
		arg.UserID,
		arg.RevokedAt,
		arg.RevocationReason,
	)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :execrows
UPDATE modura.auth_sessions
SET revoked_at = $4, revocation_reason = $5
WHERE tenant_id = $1 AND user_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	TenantID         string             `json:"tenant_id"`
	UserID           string             `json:"user_id"`
	ID               string             `json:"id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSession,
		arg.TenantID,
		arg.UserID,
		arg.ID,
		arg.RevokedAt,
		arg.RevocationReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionAfterPasswordChange = `-- name: RotateSessionAfterPasswordChange :exec
UPDATE modura.auth_sessions
SET refresh_token_hash = $2, security_version = $3, last_used_at = $4, expires_at = $5
WHERE id = $1
`

type RotateSessionAfterPasswordChangeParams struct {
	ID               string    `json:"id"`
	RefreshTokenHash []byte    `json:"refresh_token_hash"`
	SecurityVersion  int64     `json:"security_version"`
	LastUsedAt       time.Time `json:"last_used_at"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) RotateSessionAfterPasswordChange(ctx context.Context, arg RotateSessionAfterPasswordChangeParams) error {
	_, err := q.db.Exec(ctx, rotateSessionAfterPasswordChange,
		arg.ID,
		arg.RefreshTokenHash,
		arg.SecurityVersion,
		arg.LastUsedAt,
		arg.ExpiresAt,
	)
	return err
}

const rotateSessionSecret = `-- name: RotateSessionSecret :exec
UPDATE modura.auth_sessions
SET refresh_token_hash = $2, last_used_at = $3, expires_at = $4
WHERE id = $1
`

type RotateSessionSecretParams struct {
	ID               string    `json:"id"`
	RefreshTokenHash []byte    `json:"refresh_token_hash"`
	LastUsedAt       time.Time `json:"last_used_at"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) RotateSessionSecret(ctx context.Context, arg RotateSessionSecretParams) error {
	_, err := q.db.Exec(ctx, rotateSessionSecret,
		arg.ID,
		arg.RefreshTokenHash,
		arg.LastUsedAt,
		arg.ExpiresAt,
	)
	return err
}

const sessionFamilyOwner = `-- name: SessionFamilyOwner :one
SELECT tenant_id, user_id
FROM modura.auth_sessions
WHERE family_id = $1
LIMIT 1
`

type SessionFamilyOwnerRow struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) SessionFamilyOwner(ctx context.Context, familyID string) (SessionFamilyOwnerRow, error) {
	row := q.db.QueryRow(ctx, sessionFamilyOwner, familyID)
	var i SessionFamilyOwnerRow
	err := row.Scan(&i.TenantID, &i.UserID)
	return i, err
}

const sessionSecurityActive = `-- name: SessionSecurityActive :one
SELECT 1
FROM modura.auth_sessions s
JOIN modura.users u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
JOIN modura.tenants t ON t.id = s.tenant_id
WHERE s.id = $1 AND s.tenant_id = $2 AND s.user_id = $3
  AND s.security_version = $4 AND u.security_version = $4
  AND s.revoked_at IS NULL AND s.expires_at > $5
  AND u.status = 'active' AND t.status = 'active'
`

type SessionSecurityActiveParams struct {
	ID              string    `json:"id"`
	TenantID        string    `json:"tenant_id"`
	UserID          string    `json:"user_id"`
	SecurityVersion int64     `json:"security_version"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) SessionSecurityActive(ctx context.Context, arg SessionSecurityActiveParams) (int32, error) {
	row := q.db.QueryRow(ctx, sessionSecurityActive,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.SecurityVersion,
		arg.ExpiresAt,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const tenantStatusByID = `-- name: TenantStatusByID :one
SELECT status
FROM modura.tenants
WHERE id = $1
`

func (q *Queries) TenantStatusByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, tenantStatusByID, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const tenantUserByID = `-- name: TenantUserByID :one
SELECT id, username, email, status, created_at, updated_at
FROM modura.users
WHERE tenant_id = $1 AND id = $2
`

type TenantUserByIDParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type TenantUserByIDRow struct {
	ID        string      `json:"id"`
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) TenantUserByID(ctx context.Context, arg TenantUserByIDParams) (TenantUserByIDRow, error) {
	row := q.db.QueryRow(ctx, tenantUserByID, arg.TenantID, arg.ID)
	var i TenantUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenantUserStatusByID = `-- name: TenantUserStatusByID :one
SELECT status
FROM modura.users
WHERE tenant_id = $1 AND id = $2
`

type TenantUserStatusByIDParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) TenantUserStatusByID(ctx context.Context, arg TenantUserStatusByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, tenantUserStatusByID, arg.TenantID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const transitionTenantStatus = `-- name: TransitionTenantStatus :execrows
UPDATE modura.tenants
SET status = $3, updated_at = $4
WHERE id = $1 AND status = $2
`

type TransitionTenantStatusParams struct {
	ID        string    `json:"id"`
	Status    string    `json:"status"`
	Status_2  string    `json:"status_2"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) TransitionTenantStatus(ctx context.Context, arg TransitionTenantStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionTenantStatus,
		arg.ID,
		arg.Status,
		arg.Status_2,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlockTenantUser = `-- name: UnlockTenantUser :execrows
UPDATE modura.users
SET status = 'active', security_version = security_version + 1, updated_at = $3
WHERE tenant_id = $1 AND id = $2 AND status = 'locked'
`

type UnlockTenantUserParams struct {
	TenantID  string    `json:"tenant_id"`
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UnlockTenantUser(ctx context.Context, arg UnlockTenantUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlockTenantUser, arg.TenantID, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordHash = `-- name: UpdatePasswordHash :execrows
UPDATE modura.users
SET password_hash = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 'active'
`

type UpdatePasswordHashParams struct {
	TenantID     string      `json:"tenant_id"`
	ID           string      `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordHash, arg.TenantID, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSelfProfile = `-- name: UpdateSelfProfile :exec
UPDATE modura.users
SET username = $3, normalized_username = $4, email = $5, normalized_email = $6,
    email_verified_at = CASE WHEN normalized_email IS NOT DISTINCT FROM $6 THEN email_verified_at ELSE NULL END,
    updated_at = $7
WHERE tenant_id = $1 AND id = $2
`

type UpdateSelfProfileParams struct {
	TenantID           string      `json:"tenant_id"`
	ID                 string      `json:"id"`
	Username           string      `json:"username"`
	NormalizedUsername string      `json:"normalized_username"`
	Email              pgtype.Text `json:"email"`
	NormalizedEmail    pgtype.Text `json:"normalized_email"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateSelfProfile(ctx context.Context, arg UpdateSelfProfileParams) error {
	_, err := q.db.Exec(ctx, updateSelfProfile,
		arg.TenantID,
		arg.ID,
		arg.Username,
		arg.NormalizedUsername,
		arg.Email,
		arg.NormalizedEmail,
		arg.UpdatedAt,
	)
	return err
}

const updateTenantProfile = `-- name: UpdateTenantProfile :exec
UPDATE modura.tenants
SET display_name = $2, updated_at = $3
WHERE id = $1
`

type UpdateTenantProfileParams struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"display_name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTenantProfile(ctx context.Context, arg UpdateTenantProfileParams) error {
	_, err := q.db.Exec(ctx, updateTenantProfile, arg.ID, arg.DisplayName, arg.UpdatedAt)
	return err
}

const userExistsInTenant = `-- name: UserExistsInTenant :one
SELECT EXISTS (SELECT 1 FROM modura.users WHERE tenant_id = $1 AND id = $2) AS present
`

type UserExistsInTenantParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) UserExistsInTenant(ctx context.Context, arg UserExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsInTenant, arg.TenantID, arg.ID)
	var present bool
	err := row.Scan(&present)
	return present, err
}
