// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package authorizationdb

import (
	"context"
	"time"
)

const initializeUserRoleVersion = `-- name: InitializeUserRoleVersion :execrows
INSERT INTO wheretolive.user_role_versions (tenant_id, user_id, version, updated_at)
VALUES ($1, $2, 1, $3)
ON CONFLICT (tenant_id, user_id) DO NOTHING
`

type InitializeUserRoleVersionParams struct {
	TenantID  string    `json:"tenant_id"`
	UserID    string    `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InitializeUserRoleVersion(ctx context.Context, arg InitializeUserRoleVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, initializeUserRoleVersion, arg.TenantID, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockUserRoleVersion = `-- name: LockUserRoleVersion :one
SELECT version
FROM wheretolive.user_role_versions
WHERE tenant_id = $1 AND user_id = $2
FOR UPDATE
`

type LockUserRoleVersionParams struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) LockUserRoleVersion(ctx context.Context, arg LockUserRoleVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserRoleVersion, arg.TenantID, arg.UserID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const nonReservedRoleIDsByUser = `-- name: NonReservedRoleIDsByUser :many
SELECT ur.role_id
FROM wheretolive.user_roles ur
JOIN wheretolive.roles r ON r.tenant_id = ur.tenant_id AND r.id = ur.role_id
WHERE ur.tenant_id = $1 AND ur.user_id = $2 AND r.reserved = false
ORDER BY ur.role_id
`

type NonReservedRoleIDsByUserParams struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) NonReservedRoleIDsByUser(ctx context.Context, arg NonReservedRoleIDsByUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, nonReservedRoleIDsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userRoleVersion = `-- name: UserRoleVersion :one

SELECT version
FROM wheretolive.user_role_versions
WHERE tenant_id = $1 AND user_id = $2
`

type UserRoleVersionParams struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

// Authorization-owned queries. The users table belongs to the identity
// module; account existence is verified through identity's public API.
func (q *Queries) UserRoleVersion(ctx context.Context, arg UserRoleVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, userRoleVersion, arg.TenantID, arg.UserID)
	var version int64
	err := row.Scan(&version)
	return version, err
}
